package com.potterlim.daylog.support;

import java.util.ArrayList;
import java.util.List;
import org.springframework.stereotype.Component;
import org.springframework.web.util.HtmlUtils;

@Component
public class SimpleMarkdownRenderer {

    /**
     * Renders the markdown subset used by this application into safe HTML.
     *
     * <p>Preconditions: the input may be blank. The renderer supports headers, bullet lists, and
     * checkbox-style list items because those are the only markdown constructs generated by the
     * application itself.</p>
     *
     * @return HTML markup safe to inject into the Thymeleaf view with {@code th:utext}.
     */
    public String renderMarkdown(String markdownTextOrNull) {
        if (markdownTextOrNull == null || markdownTextOrNull.isBlank()) {
            return "";
        }

        StringBuilder htmlBuilder = new StringBuilder();
        List<String> paragraphLines = new ArrayList<>();
        boolean isListOpen = false;

        for (String line : splitLines(markdownTextOrNull)) {
            if (line.isBlank()) {
                flushParagraph(htmlBuilder, paragraphLines);
                if (isListOpen) {
                    closeList(htmlBuilder);
                    isListOpen = false;
                }
                continue;
            }

            if (line.startsWith("#")) {
                flushParagraph(htmlBuilder, paragraphLines);
                if (isListOpen) {
                    closeList(htmlBuilder);
                    isListOpen = false;
                }
                appendHeader(htmlBuilder, line);
                continue;
            }

            if (line.startsWith("- [x] ") || line.startsWith("- [X] ") || line.startsWith("- [ ] ")) {
                flushParagraph(htmlBuilder, paragraphLines);

                if (!isListOpen) {
                    htmlBuilder.append("<ul>");
                    isListOpen = true;
                }

                appendCheckboxListItem(htmlBuilder, line);
                continue;
            }

            if (line.startsWith("- ")) {
                flushParagraph(htmlBuilder, paragraphLines);

                if (!isListOpen) {
                    htmlBuilder.append("<ul>");
                    isListOpen = true;
                }

                htmlBuilder.append("<li>")
                    .append(HtmlUtils.htmlEscape(line.substring(2).trim()))
                    .append("</li>");
                continue;
            }

            if (isListOpen) {
                closeList(htmlBuilder);
                isListOpen = false;
            }
            paragraphLines.add(HtmlUtils.htmlEscape(line));
        }

        flushParagraph(htmlBuilder, paragraphLines);
        if (isListOpen) {
            closeList(htmlBuilder);
        }
        return htmlBuilder.toString();
    }

    private static void appendHeader(StringBuilder htmlBuilder, String line) {
        int headerLevel = 0;

        while (headerLevel < line.length() && line.charAt(headerLevel) == '#') {
            headerLevel++;
        }

        int normalizedHeaderLevel = Math.min(headerLevel, 6);
        String headerText = line.substring(headerLevel).trim();

        htmlBuilder.append("<h")
            .append(normalizedHeaderLevel)
            .append(">")
            .append(HtmlUtils.htmlEscape(headerText))
            .append("</h")
            .append(normalizedHeaderLevel)
            .append(">");
    }

    private static void appendCheckboxListItem(StringBuilder htmlBuilder, String line) {
        boolean isChecked = line.regionMatches(true, 0, "- [x] ", 0, 6);
        String itemText = line.substring(6).trim();

        htmlBuilder.append("<li>")
            .append("<input type=\"checkbox\" disabled")
            .append(isChecked ? " checked" : "")
            .append(" /> ")
            .append(HtmlUtils.htmlEscape(itemText))
            .append("</li>");
    }

    private static void closeList(StringBuilder htmlBuilder) {
        htmlBuilder.append("</ul>");
    }

    private static void flushParagraph(StringBuilder htmlBuilder, List<String> paragraphLines) {
        if (paragraphLines.isEmpty()) {
            return;
        }

        htmlBuilder.append("<p>")
            .append(String.join("<br />", paragraphLines))
            .append("</p>");

        paragraphLines.clear();
    }

    private static String[] splitLines(String text) {
        return text.replace("\r\n", "\n").replace('\r', '\n').split("\n", -1);
    }
}
