spring:
  application:
    name: dayLog
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  thymeleaf:
    cache: true
server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        same-site: lax
day-log:
  storage:
    logs-root-path: ${DAY_LOG_LOGS_ROOT_PATH:logs}
  security:
    remember-me-key: ${DAY_LOG_REMEMBER_ME_KEY}
    remember-me-cookie-name: ${DAY_LOG_REMEMBER_ME_COOKIE_NAME:DAY_LOG_REMEMBER_ME}
    remember-me-token-validity-seconds: ${DAY_LOG_REMEMBER_ME_TOKEN_VALIDITY_SECONDS:1209600}
