package com.potterlim.daymark.entity;

public enum EOperationEventType {
    USER_REGISTERED,
    SIGN_IN_SUCCEEDED,
    SIGN_IN_FAILED,
    EMAIL_VERIFICATION_RESEND_REQUESTED,
    EMAIL_VERIFICATION_MAIL_SENT,
    EMAIL_VERIFICATION_MAIL_FAILED,
    EMAIL_VERIFIED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_MAIL_SENT,
    PASSWORD_RESET_MAIL_FAILED,
    PASSWORD_RESET_COMPLETED,
    MORNING_PLAN_VIEWED,
    MORNING_PLAN_SAVED,
    EVENING_REVIEW_VIEWED,
    EVENING_REVIEW_SAVED,
    WEEKLY_REVIEW_VIEWED,
    RECORD_LIBRARY_VIEWED,
    RECORD_PREVIEW_VIEWED,
    MARKDOWN_EXPORTED,
    PDF_EXPORT_VIEWED
}
