package com.potterlim.daymark.entity;

public enum EOperationEventType {
    USER_REGISTERED,
    SIGN_IN_SUCCEEDED,
    SIGN_IN_FAILED,
    MORNING_PLAN_VIEWED,
    MORNING_PLAN_SAVED,
    EVENING_REVIEW_VIEWED,
    EVENING_REVIEW_SAVED,
    WEEKLY_REVIEW_VIEWED,
    RECORD_LIBRARY_VIEWED,
    RECORD_PREVIEW_VIEWED,
    MARKDOWN_EXPORTED,
    PDF_EXPORT_VIEWED
}
