delete from operation_usage_event
where event_type in (
    'EMAIL_VERIFICATION_RESEND_REQUESTED',
    'EMAIL_VERIFICATION_MAIL_SENT',
    'EMAIL_VERIFICATION_MAIL_FAILED',
    'EMAIL_VERIFIED',
    'PASSWORD_RESET_REQUESTED',
    'PASSWORD_RESET_MAIL_SENT',
    'PASSWORD_RESET_MAIL_FAILED',
    'PASSWORD_RESET_COMPLETED'
);
