create table daily_log_entry (
    id bigint not null auto_increment,
    user_account_id bigint not null,
    log_date date not null,
    has_morning_log bit not null,
    has_evening_log bit not null,
    goals_text text not null,
    focus_text text not null,
    challenges_text text not null,
    evening_goals_text text not null,
    achievements_text text not null,
    improvements_text text not null,
    gratitude_text text not null,
    notes_text text not null,
    created_at datetime(6) not null,
    updated_at datetime(6) not null,
    constraint pk_daily_log_entry primary key (id),
    constraint fk_daily_log_entry_user_account foreign key (user_account_id) references user_account (id),
    constraint uk_daily_log_entry_user_account_id_log_date unique (user_account_id, log_date)
);
